### M2 T01: Graphical visualization of a dataset

This series of exercises complements the data exploration techniques through graphic visualization using the Matplotlib and Searborn libraries.

### Level 1

#### Exercise 1
In this exercise we will work with the filtered dataset obtained in activity M1 T02 (DF_Filtered). Different graphic representations will be created in order to gain competencies and expertise with the libraries.

In [2]:
# Importing data structures and data analisys libraries
import pandas as pd
import numpy as np

# Importing plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Float format definition
pd.options.display.float_format = '{:.1f}'.format

In [5]:
#Load filtered Airlines Delays dataset
df = pd.read_csv("../Modul_1/DF_Filtered.csv")

,Unnamed: 0,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,ActualElapsedTime,CRSElapsedTime,AirTime,...,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,DepDate,AverageSpeed,Status
0,0,4,2003.0,1955,2211.0,2225,WN,128.0,150.0,116.0,...,N,0,NaN,NaN,NaN,NaN,NaN,2008-01-03,674.3,0.0
1,1,4,754.0,735,1002.0,1000,WN,128.0,145.0,113.0,...,N,0,NaN,NaN,NaN,NaN,NaN,2008-01-03,692.2,0.0
2,2,4,628.0,620,804.0,750,WN,96.0,90.0,76.0,...,N,0,NaN,NaN,NaN,NaN,NaN,2008-01-03,654.3,0.0

In [ ]:
df.head(3)